site_name: VSFGA

# repo_url: https://github.com/Diogo-Barboza/ProgrammingCodes

plugins: 
  - search

nav:
  - Home: index.md
  - 2024.2: 
    - Requisitos: sections/2024.2/Requisitos.md
    - EDA: sections/2024.2/EDA.md
    - FAC: sections/2024.2/FAC.md
  - 2025.1:
    - EDA: 
      - Ementa: sections/2025.1/EDA1/ementa.md
      - BigO: sections/2025.1/EDA1/bigO.md
      - Recursão: sections/2025.1/EDA1/recursao.md
      - Ponteiros: sections/2025.1/EDA1/ponteiro.md
      - Algoritmos de Busca: sections/2025.1/EDA1/busca.md
      - Algoritmos de Ordenação: sections/2025.1/EDA1/ordenacao.md
    - SDB2: sections/2025.1/SDB2/ementa.md
    - Testes de Software:
      - Ementa: sections/2025.1/Testes/ementa.md
      - Black Box: sections/2025.1/Testes/BlackBox.md
    - IHC: sections/2025.1/IHC/ementa.md
    - Arquitetura e Desenho de Software: 
      - Ementa: sections/2025.1/ADS/ementa.md
      - Contextualização: sections/2025.1/ADS/cont.md
      - BPMN: sections/2025.1/ADS/bpmn.md
  - Treinos:
    - Início: sections/treino/treinoshome.md
    - Peito e Tríceps: sections/treino/A.md
    - Costas e Bíceps: sections/treino/B.md
    - Perna Completo: sections/treino/C.md
    - Ombro, Trapézio e Abdômen: sections/treino/D.md
  - HackaTruck:
    - Conteúdo: sections/hackatruck/cursoEAD/conteudo.md
    
theme:
  name: material
  language: pt-BR
  logo: assets/logo3.png
  favicon: assets/favicon.png
  palette: 
    #Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: cyan
      toggle:
        icon: material/toggle-switch
        name: Modo escuro

    #White mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: cyan
      toggle:
        icon: material/toggle-switch-off-outline
        name: Modo claro

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - content.code.copy
    - toc.integrate
    - content.tabs.link
    - header.autohide
  
markdown_extensions:
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - markdown.extensions.attr_list

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/gerador.js
